<?php

namespace Tests\Unit;

use App\User;
use DB;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class ExampleTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        DB::enableQueryLog();
    }

    public function tearDown(): void
    {
        $log = print_r(DB::getQueryLog(), true);

        parent::tearDown(); // TODO: Change the autogenerated stub

        self::output($log);
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {

        $benchmark = new \Lavoiesl\PhpBenchmark\Benchmark();
        $benchmark->setCount(1);

//        $benchmark->add('index有り5万件', function () {
//            /*
//             * 1755ms
//             */
//            User::query()
//                ->where('type_kind_2_index', 1)
//                ->get();
//        });
//        $benchmark->add('index有り1万件', function () {
//            /*
//             * 8850ms
//             */
//            User::query()
//                ->where('type_kind_10_index', 1)
//                ->get();
//        });
//        $benchmark->add('index有り1万件のうち先頭10件', function () {
//            /*
//             * 326ms
//             */
//            User::query()
//                ->where('type_kind_10_index', 1)
//                ->take(10)
//                ->get();
//        });
//        $benchmark->add('where無しoffsetは早い？', function () {
//            /*
//             * 2319ms
//             */
//            User::query()
//                ->offset(99990)
//                ->take(10)
//                ->get();
//        });
//        $benchmark->add('複合where', function () {
//            /*
//             * 1852ms
//             */
//            User::query()
//                ->where('type_kind_10_index', 1)
//                ->where('type_kind_2_index', 1)
//                ->get();
//        });
//        $benchmark->add('user一人', function () {
//            /*
//             * 3ms
//             */
//            User::query()
//                ->where('id', 50000)
//                ->get();
//        });
//        $benchmark->add('detailをwhereHas', function () {
//            /*
//             * 604ms
//             */
//            User::whereHas('details', function($q) {
//                $q->where('seq_index', 50000);
//            })
//                ->get();
//        });
//        $benchmark->add('detailをjoin', function () {
//            /*
//             * 6ms
//             */
//            User::join('user_details', 'users.id', '=', 'user_details.user_id')
//                ->where('user_details.seq_index', 50000)
//                ->get();
//        });
        $benchmark->add('detailをwith', function () {
            /*
             * 7ms
             */
            User::where('id', 50000)
                ->with('details')
                ->get();
        });

        $benchmark->run();
    }

    private static function output($text)
    {
        fwrite(STDERR, $text);
    }
}
